services:
  - type: web
    name: nusantaravision-food-classifier
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
